const user = {
    noAuth: 'Authorization token required.',
    notAuthorized: 'You are not authorised to perform this task',
    tokenExpire: 'Token Expired',
    noAccount: 'No account registered with this username',
    ownAccountBlock: 'Your account has been blocked by admin',
    ownAccountDelete: 'Your account has been deleted by admin',
    loggedInAnotherDevice: 'Your account is already active on another device. Please logout from there first.',
    phoneAlreadyExist: 'This phone number already exist.',
    phoneNotExist: 'This phone number not exist.',
    invalidOtp: "Invalid OTP, please try again.",
    emailAlreadyExist: "This email address is already registered.",
    accountAlreadyExist: 'An account with this email or phone already exists.',
    forgotMailSent: 'Check your email for password reset.',
    emailNotRegis: 'This email address is not registered with us.',
    forgotLinkExipre: 'Forgot link expired.',
    passChanged: 'Password changed successfully. Please login again.',
    logout: 'Logged-out successfully.',
    validOldPass: 'Please enter valid old password.',
    verifyOtp: "OTP verified successfully.",
    register: 'User register successfully.',
    otpSent: 'A one-time password (OTP) has been sent to your registered email address',
    verifiedEmail: 'Account verified successfully.',
    logOut: 'Account logged out successfully.',
    sendOtp: "OTP has been resent successfully.",
    userNotExist: 'User not exist.',
    invalidPassOrEmail: 'Please enter valid email or password.',
    loggedIn: 'Logged-in successfully.',
    passwordReset: 'Password reset successfully.',
    profileUpdated: 'Profile updated successfully.',
    getProfile: 'Profile detail fetched successfully.',
    accountDeleted: 'Account deleted successfully.',
    emailExist: 'Email already exist.',
    userDetail: 'User details fetched successfully.',
    userNot: "User not found.",

    profileAlreadyCompleted: 'Profile is already completed.',
    validObjectId: 'Required valid object Id',
}

export default { user }