default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"],
      is_key_content_base64: false,
      in_house: false
    )

    setup_ci

    # Fetch certificates and profiles
    keychain_path = File.expand_path("~/Library/Keychains/#{ENV['MATCH_KEYCHAIN_NAME']}-db")
    
    cert(
      keychain_path: keychain_path,
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"]
    )
    sigh(force: true)
    
    # Inject the profile into the Xcode project
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "FastMatch.xcodeproj"
    )
    
    update_project_provisioning(
      xcodeproj: "FastMatch.xcodeproj",
      profile: ENV["SIGH_PROFILE_PATH"],
      target_filter: "FastMatch",
      build_configuration: "Release"
    )

    # Build the app using Fastlane's smart defaults
    build_app(
      workspace: "FastMatch.xcworkspace",
      scheme: "FastMatch",
      export_method: "app-store",
      clean: true,
      xcargs: {
        "CODE_SIGN_IDENTITY" => "Apple Distribution",
        "CODE_SIGN_IDENTITY[sdk=iphoneos*]" => "Apple Distribution",
        "CODE_SIGN_STYLE" => "Manual",
        "PROVISIONING_PROFILE_SPECIFIER" => ENV['SIGH_NAME']
      }
    )

    # Upload to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
