import { Document } from "mongoose"

export interface UserInterface extends Document {
    email: string,
    phone: string,
    password: string,
    deviceType: string,
    deviceToken: string,
    fcmToken: string,
    fullName: string,
    displayName: string,
    socketId: string,
    profilePicture: string,
    interests: string[],
    isVerified: boolean,
    isOnline: boolean,
    isLogin: boolean,
    gender: 'male' | 'female' | 'other',
    preference: 'everyone' | 'male' | 'female',
    dateOfBirth: Date,
    otp: number,
    forgotToken: string,
    role: 'user' | 'admin',
    isPremium: 'free' | 'premium',
    deviceId?: string,
    loginSessionId?: string,
    deviceName?: string,
    platform?: 'android' | 'ios',
    blockedUsers: any[],
    age?: string,
    location?: string,
    language?: string,
    totalRatingScore: number,
    ratingCount: number,
    lastOnlineNotificationAt?: Date,
    dailyMatchCount?: number,
    dailyMatchDate?: Date,
    subscriptionPlan: 'monthly' | 'yearly' | null,
    subscriptionExpiresAt?: Date,
    isProfileComplete: boolean,
    isBanned: boolean,
    blockedCalls: any[],
    skippedUsers: Array<{ userId: any; skippedAt: Date }>,
    walletBalance: number,
    trustScore: number,
    lastRewardClaimedAt?: Date,
    loginStreak: number,
    publicKey?: string,
}